### ISSUE TITLE
2.0 啥时候上线？

### ISSUE THREAD

**Issue by Liaoer** [SuperCLine/actioneditor#3]

**Comment by SuperCLine** [comment]
早已提交了，应该就在这几天审核过吧，审核过了第一时间告知。

Mr.Liao <notifications@github.com> 于2020年3月10日周二 下午5:49写道：

**Comment by SuperCLine** [comment]
https://assetstore.unity.com/packages/templates/systems/cline-action-editor-2-163343

**Comment by SuperCLine** [comment]
version 2.0:
https://assetstore.unity.com/packages/templates/systems/cline-action-editor-2-163343
Video tutorial: https://youtu.be/CQNw-9yXzMM or
https://www.bilibili.com/video/av94687678/

apple fan <xfanapple@gmail.com> 于2020年3月12日周四 上午9:55写道：

**Comment by SuperCLine** [comment]
version 2.0:
https://assetstore.unity.com/packages/templates/systems/cline-action-editor-2-163343
Video tutorial: https://youtu.be/CQNw-9yXzMM or
https://www.bilibili.com/video/av94687678/

Mr.Liao <notifications@github.com> 于2020年3月10日周二 下午5:49写道：

**Comment by Liaoer** [comment]
为啥成了一个全新的产品？不是在已有的产品生升级版本么？

**Comment by SuperCLine** [comment]
你登录asset store后，就是自动升级啊，不会坑前期支持的兄弟的，放心！

Mr.Liao <notifications@github.com> 于2020年3月30日周一 下午5:13写道：
